name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
      options: --privileged
    steps:
      # - name: Start Docker daemon
      #   run: |
      #     dockerd &
      #     sleep 5

      - name: Install dependencies
        run: apk add --no-cache git go docker-compose

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start dependencies
        run: docker-compose -f ci/compose.yml up -d

      - name: Run tests
        run: go test -v ./... -count=1
