name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start dependencies
        run: docker run -d --name ci-redis -p 6379:6379 redis

      # - name: Install redis-cli
      #   run: sudo apt --update add redis

      # - name: Is it alive?
      #   run: |
      #     for i in $(seq 1 20); do
      #       if redis-cli ping | grep -q PONG; then
      #         echo "Redis is ready"
      #         break
      #       fi
      #       sleep 1
      #     done

      - name: Run tests
        run: go test -v ./...
